### ISSUE TITLE
rethinkdb_exporter image on Docker Hub

### ISSUE THREAD

**Issue by alexmbird** [oliver006/rethinkdb_exporter#12]
Perhaps related to #8 - for my use case (deploying to a k8s cluster via a Helm chart) it would be valuable to have a standard Docker image for rethinkdb_exporter published on Docker Hub.

If you can create a namespace/repository for it I'll be happy to contribute the plumbing for releases.

**Comment by oliver006** [comment]
Yeah, I started work on that last night but something wasn't working but it should be fixed now.
https://github.com/oliver006/rethinkdb_exporter/releases/tag/v0.4.3 is the first release that was automatically built and pushed to the docker registry here: https://hub.docker.com/r/oliver006/rethinkdb_exporter/tags/

Last thing left to do: add docker instructions to the README, I'll get to that later today.

**Comment by oliver006** [comment]
Done via https://github.com/oliver006/rethinkdb_exporter/commit/c1ea9a9587940edce31cd19cc011f148d78c23e2
