### ISSUE TITLE
Explicit Project License?

### ISSUE THREAD

**Issue by johnke** [oliver006/rethinkdb_exporter#16]
Should this project have an explicit license associated with it? Without an explicit license, [the implicit license prohibits users from distributing the code](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#what-happens-if-i-dont-choose-a-license) (which ultra-bureaucratic $DAYJOB is interpreting as "cannot install onto servers").

**Comment by oliver006** [comment]
Thanks for raising this issue, I can (and probably should have already) add a license to this project, probably the MIT license. Does that work for you and your $DAYJOB ?

**Comment by johnke** [comment]
MIT is plenty for us! Thanks!

**Comment by oliver006** [comment]
Added via https://github.com/oliver006/rethinkdb_exporter/commit/cdbf37e8f99da1a1594a2b657cb69cd319266e9f

Let me know if there's anything else!
