### ISSUE TITLE
Grafana displays nothing

### ISSUE THREAD

**Issue by Koyamie** [oliver006/rethinkdb_exporter#18]
Hey, I did all the steps to install and added grafana dahsboard and nothing works.

I can acceed to localhost:9123, everything is displayed and works but I can not acceed to it on grafana, any solution ?

Thanks

**Comment by oliver006** [comment]
Di you confirm in Prometheus that the rethinkdb_exporter is being scraped successfully and that the timeseries are there?
Without more information about your setuo (configs, console & error logs, etc) it's impossible to say what's going one.

**Comment by Koyamie** [comment]
No they are not, only go_ related metrics are available in Pormetheus.
Other timeseries are not here.

My only log is that rethinkdb_exporter is listening at :9123

My config is ` --db.auth=admin --db.pass mypassword`

**Comment by oliver006** [comment]
Anything in the console logs?

**Comment by Koyamie** [comment]
Nothing else than the listening line sadly

**Comment by oliver006** [comment]
Hmm, there should be log output when you access the /metrics endpoint and the exporter is trying to access the DB.

**Comment by Koyamie** [comment]
There is absolutly no logs even when accessing to the /metrics endpoint

**Comment by oliver006** [comment]
Where's your DB running?

**Comment by Koyamie** [comment]
on my server, same from prometheus and rethinkdb_exporter

**Comment by Koyamie** [comment]
That was my bad, didn't add job to prom, sry
