### ISSUE TITLE
Please don't count my rows

### ISSUE THREAD

**Issue by analytik** [oliver006/rethinkdb_exporter#2]
`res, err := r.DB(s.DB).Table(s.Table).Count().Run(sess)`

Counting table rows is a horrible idea, as it's currently not very optimized in RethinkDB and can take several seconds for larger tables. (1s for 4M rows on 3 nodes - and that's all only since we have it all cached in memory.)

This should be optional, and turned off by default.

**Comment by oliver006** [comment]
Ugh, ok, good point.
I checked the docs re: the systems tables (https://rethinkdb.com/docs/system-tables/) but it doesn't look like there's an easy way to get those stats from there so we'll make it configurable.

However, I think I'd want it to default to `on` to keep things backwards compatible and not turn off metrics collection for people. Thoughts?

**Comment by analytik** [comment]
Yeah, that makes sense, compatibility takes priority.

I'm pretty sure RethinkDB guys plan to improve the row counting situation, I saw some discussions around it, but not sure if it's scheduled yet.

Either way, for now I compiled my own version, so it's not affecting us anymore. Thanks for the response!

**Comment by oliver006** [comment]
👍

**Comment by oliver006** [comment]
#3 should address this.
