### ISSUE TITLE
Compile error with alpine 3.2

### ISSUE THREAD

**Issue by origama** [oliver006/rethinkdb_exporter#4]
Hi,
I got the same error reported in the following link during building:

https://github.com/bosun-monitor/bosun/issues/1360

Looks like you need go 1.5 to compile it properly but that's not available for alpine 3.2. Trying to use alpine:latest won't work due to a regression in go 1.7.

I solved  by using alpine 3.3

**Comment by oliver006** [comment]
Using alpine:latest now and not building inside the Docker image - closing.
